FROM python:3.6-alpine
LABEL maintainer="Dave MVONDO"
RUN addgroup -S dave && adduser -S dave -G dave -D
WORKDIR /opt
RUN apk update && pip install flask
ADD . /opt/
VOLUME /opt
EXPOSE 8080
ENV ODOO_URL="https://www.odoo.com/"
ENV PGADMIN_URL="https://www.pgadmin.org/"
ENTRYPOINT ["python3","./app.py"]
