apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
    env: prod
  name: postgres
  namespace: ic-webapp
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres
  type: ClusterIP
