prod:
  children:
    odoo:
      hosts:
        odoo_server:
    ic_webapp:
      hosts:
        ic_webapp_server:
    pg_admin:
      hosts:
        pg_admin_server:         
dev:
  children:
    odoo_dev:
      hosts:
        odoo_server_dev:
    ic_webapp_dev:
      hosts:
        ic_webapp_server_dev:
    pg_admin_dev:
      hosts:
        pg_admin_server_dev: